version: '3.8'

services:

  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - tracking-network

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foracesso
      POSTGRES_USER: root
      POSTGRES_PASSWORD: b@ncoPostgr3SQL
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - tracking-network
    restart: unless-stopped

  rabbitmq:
    build: ./messaging-broker
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tracking-network

  foracesso-module:
    build: ./foracesso-module
    container_name: foracesso-module
    ports:
      - "8081:8081"
    depends_on:
      - discovery
    networks:
      - tracking-network

  rules-service:
    build: ./rules-service
    container_name: rules-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - postgres
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      SPRING_R2DBC_POSTGRES_URL: r2dbc:postgresql://postgres:5432/foracesso
      SPRING_R2DBC_POSTGRES_USERNAME: root
      SPRING_R2DBC_POSTGRES_PASSWORD: b@ncoPostgr3SQL
      SPRING_SQL_INIT_MODE: always

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - tracking-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - rabbitmq
    networks:
      - tracking-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tracking-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - tracking-network
    restart: unless-stopped

networks:
  tracking-network:
    name: tracking-network
