version: '3.8'

services:

  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - tracking-network

  config-server:
    build: ./tracking-config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    env_file:
      - ./tracking-config-server/.env   # usa o .env do serviço (GITHUB_USER/TOKEN)
    networks:
      - tracking-network
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foracesso
      POSTGRES_USER: root
      POSTGRES_PASSWORD: b@ncoPostgr3SQL
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - tracking-network
    restart: unless-stopped

  rabbitmq:
    build: ./messaging-broker
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tracking-network

  foracesso-module:
    build: ./foracesso-module
    container_name: foracesso-module
    ports:
      - "8081:8081"
    depends_on:
      - discovery
    networks:
      - tracking-network

  rules-service:
    build: ./rules-service
    container_name: rules-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - postgres
      - config-server
      - rabbitmq
    env_file:
      - ./.env
    environment:
      SPRING_APPLICATION_NAME: "rules-service"
      SPRING_CONFIG_IMPORT: "optional:configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    networks:
      - tracking-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - rabbitmq
    networks:
      - tracking-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - discovery
      - rules-service
      - gateway
      - foracesso-module
    networks:
      - tracking-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - tracking-network
    restart: unless-stopped

networks:
  tracking-network:
    name: tracking-network
