version: '3.8'

services:

  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - tracking-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foracesso
      POSTGRES_USER: root
      POSTGRES_PASSWORD: b@ncoPostgr3SQL
    networks:
      - tracking-network

  rabbitmq:
    build: ./messaging-broker
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tracking-network

  foracesso-module:
    build: ./foracesso-module
    container_name: foracesso-module
    ports:
      - "8081:8081"
    depends_on:
      - discovery
    networks:
      - tracking-network

  rules-service:
    build: ./rules-service
    container_name: rules-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - postgres
    networks:
      - tracking-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - rabbitmq
    networks:
      - tracking-network

networks:
  tracking-network:
    name: tracking-network
