global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'discovery:8761'
          - 'gateway:8080'
          - 'foracesso-module:8081'
          - 'rules-service:8082'