global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-micrometer'
    eureka_sd_configs:
      - server: 'http://discovery:8761/eureka'
    
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
        
      - source_labels: [__meta_eureka_app_name]
        target_label: job

      - source_labels: [__meta_eureka_app_instance_metadata_management_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}/actuator/prometheus